# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thomas Cullen
email: hello@thomascullen.io
description: > # this means to ignore newlines until "baseurl:"
  Web developer & designer with a passion for user experience.
  You can see the latest projects I'm working on here, read my code here and
  get snippets of my thoughts here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thomascullen.io" # the base hostname & protocol for your site
twitter_username: thomasauros
github_username:  thomascullen

# Build settings
markdown: kramdown
